"""empty message

Revision ID: 82e60b7b157c
Revises: 9512637b5209
Create Date: 2019-04-06 12:16:19.455235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e60b7b157c'
down_revision = '9512637b5209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('abr', sa.String(length=28), nullable=True))
    op.create_index(op.f('ix_event_abr'), 'event', ['abr'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_abr'), table_name='event')
    op.drop_column('event', 'abr')
    # ### end Alembic commands ###
